### ISSUE TITLE
Replpad is unavailable if latest build fails or is in progress

### ISSUE THREAD

**Issue by hostilefork** [hostilefork/replpad-js#19]
The mechanism of asking git for the latest commit and using it has a clear flaw: Git gets the commit before Travis has finished building.

Even if the build is successful (sometimes it is not, and has to be fixed up) there will be a period of time between the commit and build finishing where the binaries are not ready.

One easy tweak that could help for most cases would be if multiple recent commit IDs were fetched (can this be done with a single GitHub query?), and the commit picked to be used would be one that had been around for a reasonable amount of time (an hour or so?)

More complex approaches could employ a fallback scheme, and "back off" on the requests (if a commit ID gives something Travis says isn't there, ask GitHub for the previous commit, and keep stepping back until successful).

**Comment by hostilefork** [comment]
Adding @BrianOtto on this...[who had said](https://github.com/metaeducation/ren-c/pull/948#issuecomment-470165682):

> Maybe there is a use case I am not understanding, but otherwise, I don't think you should be pulling the library from a remote host at all. It slows the loading of the page down and no one wants to be dependent on a third party server to run the REPL. The libr3.js library should be built offline and included in each replpad-js release. Then the file is always served locally and has been tested with the release you are using.
>
> If you are testing replpad-js with a local build of libr3.js then you can always change the library path temporarily, on your local copy only.

I would agree that ultimately, almost no users would want the general instability of a latest build.  But I'd question the "nobody" part of this.  Especially because hosted libraries are how people easily put together jsfiddles and such.

Obviously, pulling the latest is not going to work long term.  They'd want it versioned, pick the version they used, and not have it change unless they change it.  And we're going to want that with the tutorial as well...the latest commit should not be able to break it.  Edoc (A.k.a. BlackAttr) has suggested even that we not advance the tutorial lib use stamp unless it passes a "tutorial test suite"...showing all the examples to teach still do what they say.

So I realize negotiating the up to the minute build may end up a niche feature.  But when it comes to ReplPad itself as a focus point for design and testing, I'd like there to be something you can use in the URL itself to say "give me the latest".

@giuliolunati is hacking away on trying to make a hosted library easy to load, where all the code to do so (e.g. the fetch() calls) and the sensing of whether you need emterpreter or not is taken care of for you.  We have to work within the bounds of how emscripten does its thing, so this is nontrivial.  But I'd hope that the "hello world" is something someone could just put in a jsfiddle with no hosting concerns of their own...to me that's how learning and experimentation could get viral.

**Comment by gchiu** [comment]
Can you not do a JS HEAD (whatever that is)on the latest and if it's not there drop back to something else?

HEAD https://metaeducation.s3.amazonaws.com/travis-builds/0.16.2/libr3-02ce11a.js

**Comment by hostilefork** [comment]
> Can you not do a JS HEAD (whatever that is)on the latest and if it's not there drop back to something else?
> 
> HEAD https://metaeducation.s3.amazonaws.com/travis-builds/0.16.2/libr3-02ce11a.js

The argument that it may be doable by a mere mortal makes the better question "can *you* do a JS HEAD (whatever that is)"... :-)

I don't think a HEAD request is necessary as a separate network request.  The failure on the full request is enough.  That way you don't slow anything down in the case that it "just works", you only pay for the fallback if there's a problem.

So really the details are about where that handler goes in the code, what error message counts as the kind you should use as a trigger to fallback vs. to report, how the sequence loads...

If you want to help @giuliolunati then you can ask where he's at with it.

**Comment by giuliolunati** [comment]
Maybe [solved](https://github.com/metaeducation/ren-c/commit/7bdf6521afc2ae6fa80d022dac3a81d105755795)

**Comment by gchiu** [comment]
https://stackoverflow.com/questions/333634/http-head-request-in-javascript-ajax

```
function UrlExists(url, callback)
{
    var http = new XMLHttpRequest();
    http.open('HEAD', url);
    http.onreadystatechange = function() {
        if (this.readyState == this.DONE) {
            callback(this.status != 404);
        }
    };
    http.send();
}
```

**Comment by hostilefork** [comment]
> (Please note that now load-r3.js is maintained in docs/ folder of ren-c repo)

Seems to be working!  But on replpad's index.html, we need a link to refer to the latest version by on S3.

I don't know if the name "docs" is really a fit.  It seems like this is another thing that should probably live in the directory with the javascript extension, and be edited there.  Then, the Travis build can copy it to wherever it should be to make it a good URL to find it.  (Close to its root, I mean...)
