### ISSUE TITLE
No double hyphens in comment

### ISSUE THREAD

**Issue by giuliolunati** [hostilefork/replpad-js#2]
See https://stackoverflow.com/questions/26600092/why-are-double-hyphens-invalid-in-html-comments

I don't care that so much, but unfortunately my syntax highlighter does...

**Comment by hostilefork** [comment]
Fix'd here:

https://github.com/hostilefork/replpad-js/commit/6fbb79fc8d026b25b001cd87fae35d1a87e5f3f2

Glad you're looking into running/building this!  The errors are going to be the next big area of internal work for it, I want to get that idea that you can use JavaScript **try {...} catch {...}** to receive Rebol errors.
