### ISSUE TITLE
index.html has `--` in comment

### ISSUE THREAD

**Issue by giuliolunati** [hostilefork/replpad-js#3]
See https://stackoverflow.com/questions/26600092/why-are-double-hyphens-invalid-in-html-comments

I don't care that, but unfortunately my syntax highlighter does ...

**Comment by hostilefork** [comment]
Oops, didn't see that one.  :-/  Fixed here:

https://github.com/hostilefork/replpad-js/commit/5a6982fa8405f6dc44d341bd2a45b9bf57c71f4b

I added you to this repo, you should be able to commit to it... certainly for minor things such as this it would be fine to just go ahead and fix.

**Comment by giuliolunati** [comment]
Ok, thank you! :-)

Il gio 18 ott 2018, 17:44 Brian Dickens <notifications@github.com> ha
scritto:
