### ISSUE TITLE
`print [()]` causes an emscripten error

### ISSUE THREAD

**Issue by hostilefork** [hostilefork/replpad-js#36]
>> print [()]

The console outputs some errors including:

> libr3-e11d108.js:6687 Invalid function pointer called with signature 'viii'. Perhaps this is an invalid value (e.g. caused by calling a virtual method on a NULL pointer)? Or calling a function with an incorrect type, which will fail? (it is worth building your source files with -Werror (warnings are errors), as warnings can indicate undefined behavior which can cause this)
nullFunc_viii @ libr3-e11d108.js:6687
>
> libr3-e11d108.js:6688 Build with ASSERTIONS=2 for more info.

**Comment by gchiu** [comment]
This is actually an interpreter error as it happens in ren-c/core

**Comment by gchiu** [comment]
**    Version:2.102.0.3.40**
**    Platform:Windows win32-x64**
**    Build:27-Mar-2019/1:02:16+0:00**
**    Commit:e11d10875e7b9fd7181e7676ee1bc032d1eb0e42**
*
    print [()]

causes a hard crash
