### ISSUE TITLE
Empty input line is difficult to click

### ISSUE THREAD

**Issue by giuliolunati** [hostilefork/replpad-js#39]
On my phone when the input line is empty it has zero width and invisible border, so is very very difficult to click it to gain focus. Maybe also clicking around it (e.g. on prompt) could give it the focus?

**Comment by hostilefork** [comment]
I had some reason for doing that the way I did, initially, that I don't now remember, and things have changed.  :-(

But hopefully this addresses it?

https://github.com/hostilefork/replpad-js/commit/10eb59af452eb8c0b32e08a6c5c8c62b9b197635

**Comment by giuliolunati** [comment]
Yes, now is perfect! :-)
