### ISSUE TITLE
Location of libr3* files

### ISSUE THREAD

**Issue by giuliolunati** [hostilefork/replpad-js#4]
Placing libr3* in ../ren-c/make sure is handy in your (and mine) dev environment, but not so when we will publish elsewhere.
Should we do place them in the same folder with gui.js?

https://github.com/hostilefork/replpad-js/blob/5a6982fa8405f6dc44d341bd2a45b9bf57c71f4b/gui.js#L194

**Comment by hostilefork** [comment]
The right way to approach this is probably to have a make.r build switch telling it where you want the output library to be put.  That would mean the build cycle could put the products into **../../js-replpad/lib/rebol** and it could be in the .gitignore, etc.

It definitely needs to just be able to build and reload in one step!

**Comment by giuliolunati** [comment]
Or link them? `ln -s /path/to/libr.* /path/to/replpad-js/lib/rebol/`

**Comment by hostilefork** [comment]
My Linux VirtualBox shared folder is on a Windows host, so I can build and edit the same source enlistment in Visual Studio as well as under linux.  That configuration doesn't allow symbolic links, unfortunately--but it's important for me to have it set up that way.

**Comment by giuliolunati** [comment]
Ok

Il ven 19 ott 2018, 01:06 Brian Dickens <notifications@github.com> ha
scritto:

**Comment by giuliolunati** [comment]
Try this:
`cd replpad_js
r3 /pat/to/ren-c/make/make.r config: /path/to/ren-c/make/configs/emscripten.r <your options here>`
Should build libr3.* in cwd replpad_js
