### ISSUE TITLE
Support SCRIPT src="text/rebol" 

### ISSUE THREAD

**Issue by hostilefork** [hostilefork/replpad-js#44]
The browser apparently doesn't execute any script tags that aren't JavaScript.  It thus might be nice if any `<script src="text/rebol">...</script>` would get picked up for execution by libRebol.

I don't know if a similar thing would be possible for stylesheets, but it might be worth thinking about something there too.

**Comment by gchiu** [comment]
So, how would this work?  If you __do <someurl>__ and it contains the _text/rebol_ script it would evaluate the code between the script tags as rebol?

**Comment by giuliolunati** [comment]
That could be implemented in load-r3.js as the last step: it should search for scripts with type=text/rebol and execute they. E.g. in the index.html of replpad-js we could insert `<script type="text/rebol" src="replpad.reb"></script>`

**Comment by giuliolunati** [comment]
Also would be possible write the 99% of the page in a Rebol dialect, let call it RebMarkup: the page could be:
`<script type="text/rebol" src=rebol-markup.reb>
<script type="text/rebol-markup">
 ... RebolMarkup code here ...
</script>
<script src="load-r3.js">

**Comment by giuliolunati** [comment]
Implemented in https://github.com/metaeducation/ren-c/commit/b8a37a3284dbe40d531a85cc5fd5179484f8005a

**Comment by hostilefork** [comment]
> Implemented in metaeducation/ren-c@b8a37a3

Great!!

The functionality with script code when a tag already has `src` is a cool idea...but maybe shouldn't be relied on:

https://stackoverflow.com/questions/6528325/what-does-a-script-tag-with-src-and-content-mean

Though maybe if it works in all browsers that people use, it'd be ok.

**Comment by giuliolunati** [comment]
Hm, if it violates the standard we shouldn't use it. We should promote best practices.
