### ISSUE TITLE
replpad.reb: Error "js-native has no value" 

### ISSUE THREAD

**Issue by giuliolunati** [hostilefork/replpad-js#5]
Cloned fresh replpad-js repository from Github.
Downloaded libr.* from http://hostilefork.com/media/shared/ren-c/make
Put them in my replad-js/../ren-c/make
Added "alert(text)" in gui.js after line 234 `console.log("Running %replpad.reb")`
Got alert:

** Script Error: js-native has no value
** Where: do catch either else _ do _ trap if if handle-request handler if dispatch case switch _ wake-up either while-not _ wait do catch either else _ do do catch either else _ do _
** Near: [
    !!: js-native ~~ [
        {Temporary debug helper, se...
** Line: 257

**Comment by giuliolunati** [comment]
The same with other combinations of files from web / from repository

**Comment by giuliolunati** [comment]
Ok seems I must blame my webserver.reb -- the same tree works when served by Apache2, fail when served by webserver.reb, dunno why... :-/

**Comment by hostilefork** [comment]
Well certainly we want it to work with webserver.reb!  Update the ticket with complete setup instructions for the webserver, and I'll look into what's happening.

**Comment by giuliolunati** [comment]
Checked response headers for libr3.wasm:
webserver.reb send "Content-type: text", while Apache2 sends "Accept-Ranges: bytes". Idem for libr3.bytecode

**Comment by giuliolunati** [comment]
@hostilefork webserver.reb depends on a number of other modules... :-/

**Comment by hostilefork** [comment]
It's probably worth it to have it be possible for me to know where to enlist, configure, and run the webserver.reb!  :-)

Note that for wasm files to run (and not have the "falling back to arraybuffer", which causes the file to be fetched twice) you need to set the MIME content type:

     Content-Type: application/wasm

**Comment by hostilefork** [comment]
> E.g you could launch the online version with do <webserver>; but when in webserver.reb import 'httpd is executed, httpd.reb is searched for locally :-/

When it comes to modules, I'm open to having it do "whatever works" and then once we see the needs of the samples in practice, try and formalize/generalize it.  IMPORT can have refinements to guide its behavior, or there can be a difference between **import %httpd.reb** and **import <http>** and **import #httpd**, etc.

My biggest technical worries on modules are still binding-related :-/  https://forum.rebol.info/t/the-real-story-about-user-and-lib-contexts/764

**Comment by giuliolunati** [comment]
Corrected headers in webserver.reb, but always error :-(

**Comment by hostilefork** [comment]
** Script Error: js-native has no value

So it's trying to run the replpad code, but not thinking the JavaScript extension is being loaded?

    https://github.com/hostilefork/replpad-js/blob/2b2095851acf59117c547d5bbab82c4d15f75f1f/gui.js#L217

You could try extracting some kind of return value out of that to JavaScript to see for instance how many extensions it thought there were...

    var i = rebUnboxInteger(
        "i: 0 for-each [init quit]", extensions,
            "[load-extension ensure handle! init i: i + 1] i"
    )

**Comment by giuliolunati** [comment]
SOLVED!
My fault, I forgot webserver was processing .reb files instead of serving them.
