### ISSUE TITLE
If prompt is above a certain width it forces line break

### ISSUE THREAD

**Issue by hostilefork** [hostilefork/replpad-js#50]
This is caused by the 25px fixed constant here:

https://github.com/hostilefork/replpad-js/pull/48/files#diff-ebdab788d566fb4d07bb8d583ef2a3ceR155

So you get an unwanted line break with:

     system/console/prompt: "longprompt"

(No rush, not a huge priority...but until this is resolved, [custom `redbol>>` prompt in Redbol-mode is disabled](https://github.com/hostilefork/replpad-js/commit/3c5b6f2ad7b5b05adc70bdd86f134525c67ad7d3#diff-b509b0b6e8d01bc41f7e957d442e93c8R752)...)

**Comment by BrianOtto** [comment]
The simple solution is to change the width to 90% or less, and that should work for most prompts.

`width: 90%;`

The proper solution would require re-arranging the layout quite a bit. You would need to put the prompt and input into their own divs and wrap a container around them. Then adjust the CSS so that the input side would only take up the remaining space. It would need some experimenting to get right.

**Comment by gchiu** [comment]
prin "Enter data: " data: input

now causes the cursor to appear below the line

**Comment by BrianOtto** [comment]
Please see #51 for a quick fix that resolves both these *specific* issues.

@gchiu's example will still cause the issue if you have an app that uses longer prompts or questions.

e.g. `prin "How many pickles did Peter Piper pick?" data: input`

So I will continue to look into a proper solution ...

**Comment by hostilefork** [comment]
> So I will continue to look into a proper solution ...

Note that I'm not attached to much of anything of how it works...what's there was put together with me worrying much more about the Rebol side than the web side.

In fact I just went and looked at it, and what I thought it was doing (making a line divs for each line) it's not doing...it's putting a bunch of them with `<br>`.  There's been various hackery along the way so I don't know what happened.  :-/

Given the desire to support variable-width output, I think it's best to go with a "line" being word-wrapped.  I don't know how easy it is to show the continued lines with some kind of markup so you know they're continued, but that seems to make sense.

For this problem it seems to me that what we have is a situation where a "line" might need to be a container that holds the print content so far for the line, and then the input along with that...so basically two spans in a line?

**Comment by BrianOtto** [comment]
#52 is a proper solution and should resolve all issues now. It supports variable-width output, while also giving you the larger copy/paste area. Let me know if you run into any other issues!

**Comment by hostilefork** [comment]
Issues mentioned here appear to be resolved by the combination of:

https://github.com/hostilefork/replpad-js/commit/1973dbc8713194939a94d70480fd1c33a848b108
https://github.com/hostilefork/replpad-js/commit/39c20c6ecdd40424669077b97b300978ac0fc599
