### ISSUE TITLE
replpad-write/html is corrupted by  leading text

### ISSUE THREAD

**Issue by gchiu** [hostilefork/replpad-js#69]
>> replpad-write/html unspaced ["a " {&lt;a href="abcd"&gt;test&lt;/a&gt;}]
    a

    >> replpad-write/html unspaced [{&lt;a href="abcd"&gt;test&lt;/a&gt;}]
    test

**Comment by hostilefork** [comment]
Appears to be resolved by:

https://github.com/hostilefork/replpad-js/pull/72
