### ISSUE TITLE
evaluating lambdas at console causes different error from core

### ISSUE THREAD

**Issue by gchiu** [hostilefork/replpad-js#74]
```
>> 	do function [x] [x + 1] 1
** Script Error: + does not allow block! for its value1 argument
‌** Where: source do main
‌** Near: [x + ~~ 1]
‌** Line: 1

```

and in core we get

** Script Error: Use EVAL or APPLY to call functions arity > 0, not DO
** Where: do
** Near: [... function [x] [x + 1] ~~ 1]
** Line: 1

**Comment by hostilefork** [comment]
Fix'd:

https://github.com/hostilefork/replpad-js/commit/0230e87ec17f45b27bf1f4442330c71e73ebdeaa
